version: '3.8'

services:
  test-db:
    container_name: userapi-test-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_api_test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=100'

  test-app:
    container_name: userapi-test-app
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - tests/integration/.env.test
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - test-network

volumes:
  test-db-data:
    name: userapi-test-db-data

networks:
  test-network:
    name: userapi-test-network
